version: 0.0
os: linux
files:
  - source: ./build/libs/demo-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: ./startSpringapp.sh
    destination: /tmp
  - source: ./springapp.service
    destination: /etc/systemd/system
hooks:
  ApplicationStart:
    - location: startapp.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stopapp.sh
      timeout: 300
      runas: root
